extends:
  - '@commitlint/config-conventional'

rules:
  header-max-length:
    - 2
    - always
    - 72

  subject-empty:
    - 2
    - never
  type-empty:
    - 2
    - never

  subject-case:
    - 2
    - never
    - - sentence-case
      - start-case
      - pascal-case
      - upper-case

  subject-full-stop:
    - 2
    - never

  type-enum:
    - 2
    - always
    - - feat
      - fix
      - docs
      - chore
      - style
      - refactor
      - ci
      - test
      - revert
      - perf
      - build
