blank_issues_enabled: false
contact_links:
  - name: Security / Vulnerability
    url: mailto:julienpoirou@protonmail.com
    about: Please report security issues privately (subject: [SECURITY])
  - name: Q&A / Discussions
    url: https://github.com/julienpoirou/vagrant-docker-networks-manager/discussions
    about: Questions, ideas, and help
