name: CI

on:
  push:
    branches: [ main ]
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ruby:
    name: Ruby ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.1', '3.2', '3.3', '3.4']
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: RSpec (via Rake)
        run: bundle exec rake
      - name: RuboCop
        run: bundle exec rubocop
      - name: Build gem (sanity)
        run: gem build vagrant-docker-networks-manager.gemspec
