name: Lint Commit

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read

jobs:
  commitlint:
    if: ${{ github.actor != 'dependabot[bot]' && github.actor != 'renovate[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - run: npm i -D @commitlint/{config-conventional,cli}
      - run: |
          FROM="${{ github.event.pull_request.base.sha }}"
          TO="${{ github.sha }}"
          npx commitlint --from="$FROM" --to="$TO" --verbose
